### ISSUE TITLE
Is this a bug or did I misunderstand what the goal is ?

### ISSUE THREAD

**Issue by shellixyz** [CodingTrain/Directional-Boring#13]
![image](https://user-images.githubusercontent.com/4030264/177431247-46dce7db-2ffb-4f8b-a94a-06c9dbf703f3.png)

**Comment by shiffman** [comment]
Oh no! I changed the colors around today and must have broken it, oops! Let me see if I can fix!

**Comment by shiffman** [comment]
I am not able to reproduce the error, what OS and browser are you using? I just pushed a change in #14 which increases the size of the goal in case there's some stray pixels (it's checking color) at the border of the ground and the goal. The live site might take a few minutes to update but you can try it again when you see:

<img width="162" alt="Screen Shot 2022-07-05 at 7 27 32 PM" src="https://user-images.githubusercontent.com/191758/177433275-853ffc23-6395-4737-b333-447040786c57.png">

**Comment by shellixyz** [comment]
![image](https://user-images.githubusercontent.com/4030264/177433382-f3124b5b-6f36-4f39-986b-dd23cd4b3595.png)

**Comment by shellixyz** [comment]
I tried again and this time it worked

![image](https://user-images.githubusercontent.com/4030264/177433513-891c693c-586f-449c-80aa-e7880fe57c67.png)

**Comment by shellixyz** [comment]
I tried a dozen more times and can't reproduce the issue either anymore so it might be fixed
