### ISSUE TITLE
Perhaps on this practice mode there could be a curve showing where the drill will be in the future if the bias is kept enabled/disabled?

### ISSUE THREAD

**Issue by alin256** [CodingTrain/Directional-Boring#15]
Perhaps on this practice mode there could be a curve showing where the drill will be in the future if the bias is kept enabled/disabled?

_Originally posted by @ArztKlein in https://github.com/CodingTrain/Directional-Boring/issues/4#issuecomment-1175763530_

**Comment by ArztKlein** [comment]
I'll add this if it is approved by @shiffman

**Comment by alin256** [comment]
I just did it (started before your comment), sorry. I am trying to make a pull request, but there were some changes overnight (EU time).

Please add suggestions while I merging: https://al-digital.no/Directional-Boring/
