### ISSUE TITLE
Procedural Generation of terrain / obstacles

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Directional-Boring#2]

**Comment by shiffman** [comment]
Now includes some extra obstacles but leaving this open b/c plenty of room for improvement!

![image](https://user-images.githubusercontent.com/191758/176925323-80b9c96c-c806-4f73-a93e-6e2c113523c4.png)

**Comment by gradyh** [comment]
One cool idea for procedural terrain generation would be different geologic layers that affect the steering bias. So when you're in a "hard" layer, maybe it doesn't turn as sharply (and so on). It could be a color lookup like the collision detection.

**Comment by shiffman** [comment]
Yes! And nice wavy perlin noise layers! (I used this technique for a project many years ago, here's what it looked like!)

![image](https://user-images.githubusercontent.com/191758/176928526-303492f3-a1fa-4c3b-b98a-2ad017e50e19.png)

**Comment by alin256** [comment]
I think all but what spawned into issue #31 is already done
