### ISSUE TITLE
Interface

### ISSUE THREAD

**Issue by shiffman** [CodingTrain/Directional-Boring#3]
* [x] start and stop drill
* [x] toggle bias (keyboard control?)
* [x] retract drill

**Comment by kfahn22** [comment]
I have a reverse button working.  Do you want one?

**Comment by frnco** [comment]
Interface dimensions also deserve some love here, it's quite tiny on a high-DPI screen (About a third of the browser window's width, with default zoom). It's bad enough that I started playing at 170% zoom.

I do realize the `draw()` function callls `drill()` which means the drilling speed is tied to the framerate, meaning changing drilling speed is non-trivial, but it's still worth it to think of a way to control drilling speed. It should be especially helpful for adjusting difficulty level. It could be done either by not calling `drill` every other run of `draw` (or calling it multiple times), or by having a way to scale the change in angle/position. Seems worth checking.

**Comment by alin256** [comment]
> * retract drill

I managed to make a button to pull back until an even number of pipe lengths.
From there one can start drilling again to hopefully get a better result.

*update*:
I changed the boulders to places where you get **STUCK** instead of **LOSE**.
Seems to improve playability.

In the current version, there is a problem with removing the first segment of the well.

My version is available for testing here: https://al-digital.no/Directional-Boring/

**Comment by kfahn22** [comment]
My version reverses direction:   https://kfahn22.github.io/Directional-Boring/

(It also changes the scoring a bit.  I made it a weighted average of time and path.length

**Comment by alin256** [comment]
@kfahn22 I like your idea, but it is a bit more difficult to implement.

Currently, you seem to have a bug when going backwards with another bias (see the attached picture).
Do you want to help me with the animation of going back? I store old trajectories pieces in **oldPaths** array.
My fork is here: https://github.com/alin256/Directional-Boring 

![image](https://user-images.githubusercontent.com/7563037/177868855-74e2b777-21b1-4a39-969a-99832306a1a7.png)

**Comment by kfahn22** [comment]
@alin256 I have edited the code slightly so that the aiming lines are only visible when the drill is in forward mode as a minimal fix.  Feel free to come up with something better, though!  Thanks!

**Comment by alin256** [comment]
@kfahn22 I still have an unrealistic trajectory in the deployed version:

![image](https://user-images.githubusercontent.com/7563037/177962670-c6f7ddf2-ba01-455e-9a21-883a6042a063.png)
