### ISSUE TITLE
Speed Slider

### ISSUE THREAD

**Issue by Wranglyph** [CodingTrain/Directional-Boring#37]
Am I the only one who feels like the drill moves too fast? As far as skill games go, it's not the worst. But it's a far cry from the highly calculated pace that I imagine. I looked at the sketch code and realized that I have no idea how the loop speed is controlled; in fact I'm not even sure if javascript (or P5 in this case) even *does* loop like a traditional program.

Is it possible to implement a feature like this?

**Comment by alin256** [comment]
@Djinn-Indigo I have a new suggestion:

https://github.com/CodingTrain/Directional-Boring/issues/35#issuecomment-1200855179
