### ISSUE TITLE
The pop-ups while drilling

### ISSUE THREAD

**Issue by alin256** [CodingTrain/Directional-Boring#38]
@shiffman finally managed to get time to start watching your life stream.

The pop-up is shown while there is animation of a new pipe loaded in the machine. Should we remove them?

**Comment by shiffman** [comment]
Hey! Sorry I've been doing so many different things this last week can you remind me what this is referring to more specifically?

**Comment by alin256** [comment]
When you drill forward the interface pauses to add new pipes (with nice albeit fast animation). A viewer described it as new pullback checkpoint (which it is since currently a whole pipe is pulled at once).

During the pauses some instruction information is shown over the sky. It would be quite easy to remove if it looks weird to you.

**Comment by shiffman** [comment]
Ah right, I remember now! I think the animation is so fantastic! The instructions flashing in the sky I found distracting, they don't stay there long enough for me to read them. I would suggest removing them or else leaving the instructions permanently there? Having them start but fade away? I'm not sure what the best solution is, happy to defer to what you think!

**Comment by alin256** [comment]
@shiffman, should be better now.
