### ISSUE TITLE
Add Scoring?

### ISSUE THREAD

**Issue by kfahn22** [CodingTrain/Directional-Boring#6]
I have added a rudimentary scoring system.  (It adds a point for every advance and penalizes if drill bit goes out of bounds in x direction. 

https://editor.p5js.org/kfahn/sketches/tOVT5TEMf

To do:  add penalty for entering water

**Comment by shiffman** [comment]
Interesting! I think the first step for me is to just have 3 states: `DRILLING`, `WIN` (you made it to the end), `FAIL` (you hit an obstacle or went above ground).

I could see a numeric value paired with `WIN` -- the total length of the line.  So the goal is to make it to the end with the shortest path.

**Comment by kfahn22** [comment]
Yes, length of path is much better than number of advances!  Are you counting the water as an obstacle?

**Comment by shiffman** [comment]
There is a basic scoring mechanism now from #8
